services:
  basic_rest_api_template:
    container_name: basic_rest_api_container
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ..:/usr/src/app
    command: ["python", "run.py"]
